on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub dispatch event
      run: |
        curl --request POST 'https://api.github.com/repos/username/repository-b-name/dispatches' \
        --header 'Authorization: Bearer ${{secrets.Proen2}}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "event_type": "repository-a-updated"
        }'
