name: Repository dispatch run

push:
  branches:
    - main
jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Api
        run: |
          TOKEN=${{ secrets.MY_PAT }}
          OWNER=${{ secrets.OWNER }}
          REPO=${{ secrets.TARGET_REPO }}

          curl \
            -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/dispatches \
            -d '{"event_type":"on-demand-test","client_payload":{"env": "dev"}}'
